spring:
  application:
    name: jdbc-sql-rest-app
server:
  port: 7280

eureka:
  client:
    service-url:
      defaultZone: "https://eureka-server.apps.tanzu.vmw/eureka"
      #defaultZone: "http://localhost:8761/eureka"
